# Generated by Django 3.0.2 on 2020-01-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='status',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='status',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='no_of_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.IntegerField(blank=True),
        ),
    ]
