# Generated by Django 3.0.2 on 2020-01-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20200109_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='video_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
