# Generated by Django 3.0.2 on 2020-01-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_coupon_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Country'),
        ),
    ]
