# Generated by Django 3.0.2 on 2020-01-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20200109_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='store_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestcoupon',
            name='store_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
