# Generated by Django 3.0.2 on 2020-01-09 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20200109_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectedBrands',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Brands')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_selected_brands',
                'verbose_name_plural': 'user_selected_brands',
                'db_table': 'user_selected_brands',
            },
        ),
    ]
