# Generated by Django 3.0.2 on 2020-01-09 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_userselectedbrands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselectedbrands',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
