# Generated by Django 3.0.2 on 2020-01-10 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20200109_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Country'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
