# Generated by Django 3.0.2 on 2020-01-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20200110_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='country',
        ),
        migrations.CreateModel(
            name='BrandCountries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Brands')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Country')),
            ],
            options={
                'verbose_name': 'brand_countries',
                'verbose_name_plural': 'brand_countries',
                'db_table': 'brand_countries',
            },
        ),
    ]
