# Generated by Django 3.0.2 on 2020-01-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20200110_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='is_read',
            new_name='is_featured',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
