# Generated by Django 3.0.2 on 2020-01-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20200113_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description_ar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coupon',
            name='headline_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='title_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
