# Generated by Django 3.0.2 on 2020-01-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20200113_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='headline_ar',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='title_ar',
        ),
    ]
