# Generated by Django 3.0.2 on 2020-01-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_auto_20200114_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description_ar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coupon',
            name='headline_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
