# Generated by Django 3.0.2 on 2020-01-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_auto_20200114_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='discription_ar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
