# Generated by Django 3.0.2 on 2020-01-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_auto_20200114_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCountries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Country')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Coupon')),
            ],
            options={
                'verbose_name': 'coupon_countries',
                'verbose_name_plural': 'coupon_countries',
                'db_table': 'coupon_countries',
            },
        ),
    ]
